### ISSUE TITLE
Camera coordinate joint prediction?

### ISSUE THREAD

**Issue by wangzheallen** [zengwang430521/DecoMR#11]
May I ask is the pred_vertices in camera coordinate? 
https://github.com/zengwang430521/DecoMR/blob/726c7a13b85a0b6e5bec8f3488468bce22235d14/demo.py#L134

and will the following operations make it in root-relative coordinate and in mm unit? so that we can use the pred_keypoints_3d to calculate MPJPE with the ground truth in root-relative coordinate?

pred_keypoints_3d = smpl.get_train_joints(pred_vertices)[:, joint_mapper]
pred_pelvis = (pred_keypoints_3d[:, [2]] + pred_keypoints_3d[:, [3]]) / 2
pred_keypoints_3d = pred_keypoints_3d - pred_pelvis

**Comment by zengwang430521** [comment]
The vertices is in the SMPL model coordinate and in _m_ unit. We directly supervise the predicted vertices with the GT vertices produced by SMPL model. And I'm not sure the definition of the origin point in SMPL model.
