### ISSUE TITLE
Bent knee of the reconstructed model

### ISSUE THREAD

**Issue by Tanupvats** [zengwang430521/DecoMR#14]
Reconstructed 3d model has bent knees, although the person in the image is standing straight.
Can anyone tell why this is happening???
![bent_knee](https://user-images.githubusercontent.com/61944951/105662039-ced48f00-5ef4-11eb-88f0-cec2d75d0090.png)

**Comment by zengwang430521** [comment]
Hi, this may be caused by the imperfect performance of our model. With only a single image. it's hard for the model to estimate the location in depth axis.

This is a unsolved problem in monocular 3D human pose estimation. Incorporating more training data may alleviate this problem.
