### ISSUE TITLE
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=383 error=11 : invalid argument

### ISSUE THREAD

**Issue by zhangzhenyu-123** [zengwang430521/DecoMR#15]
when i try to running the demo ,then it happened,i don't  know  about this question ,but i install all the environments, please help me,thank you，i really need to running it .

**Comment by zengwang430521** [comment]
Hi, it seems to be a bug of pytorch. You may try the answer in this [issue](https://github.com/pytorch/pytorch/issues/15797).

**Comment by zhangzhenyu-123** [comment]
> Hi, it seems to be a bug of pytorch. You may try the answer in this [issue](https://github.com/pytorch/pytorch/issues/15797).

thank you very much!I I will try to deal with it.
