### ISSUE TITLE
(u,v) coordinates corresponding to mesh vertices

### ISSUE THREAD

**Issue by Shubhendu-Jena** [zengwang430521/DecoMR#16]
Hi,

Thanks for the great work. Do you have the (u,v) coordinates corresponding to SMPL mesh vertices in your continuous UV map? Or a script to obtain the same?

Thanks

**Comment by zengwang430521** [comment]
Hi, 

uv coordinates are contained in the corresponding _.obj_ file. The lines begin with vt mean the uv coordinates. You can download the file from [here](https://drive.google.com/drive/folders/1xWBVfQa7OZ14VgT9BVO9Lj_kDqRAcQ-e?usp=sharing). There are included in the zip file.

We uses standard obj file, so you can find the structure information and related codes easily.

**Comment by Shubhendu-Jena** [comment]
Hi. Thank you for the prompt response. However, I am sorry my confusion still persists. Among the 3 obj files inside the zip file, i.e. "reference_mesh.obj", "smpl_boundry_free_template.obj" and "smpl_fbx_template.obj", the first two have the following properties :

file_name
mtllibs
materials
meshes
vertices
mesh_list
parser

Unfortunately, I couldn't inspect the 3rd obj file i.e. "smpl_fbx_template.obj" as on importing it, the following error pops up : FileNotFoundError: [Errno 2] No such file or directory:'/media/shubhendujena/DATA/Subset_experiments/data/uv_sampler/untitled.mtl'"

I'd be grateful if you could pin point me to the obj file when I could find the (u,v) coordinates corresponding to the SMPL mesh. Basically, I wanted (x,y,z) --> (u,v) correspondences for the SMPL mesh

**Comment by zengwang430521** [comment]
Hi, "smpl_boundry_free_template.obj" contains the uv coordinates of our uv map, and  "smpl_fbx_template.obj" contains the uv coordinates of SMPL defaultuv map. This obj file is generated following the process of [DenseBody](https://github.com/Lotayou/densebody_pytorch/blob/master/PREPS.md).

Actually, to get the UV coordinates of each texture vertex, you do not need to use professional applications. With the function utils.obj_file.read_obj_full(), you can get the vertexes, faces, and texture coordinates.

**Comment by Shubhendu-Jena** [comment]
Hi, 

Thanks again for the prompt response. I am able to view the uv textures now! However, there is unfortunately still something I am confused with. I inspected the vertices corresponding to "smpl_fbx_template.obj" by loading it using  :

obj_full = read_obj_full('./data/uv_sampler/smpl_fbx_template.obj')
Vertices = obj_full['vertices']

The vertices seem to be very different from the neutral smpl model "basicmodel_neutral_lbs_10_207_0_v1.0.0.pkl". Could you please tell me why this is so and how exactly "smpl_fbx_template.obj" has been made?

Thanks in advance

**Comment by zengwang430521** [comment]
Hi, "smpl_fbx_template.obj" is generated following the process of [DenseBody](https://github.com/Lotayou/densebody_pytorch/blob/master/PREPS.md). 

And the vertices in this file is not used in our framework. We only use the faces and texture coordinates to get the mapping function between mesh and UV space.

**Comment by Shubhendu-Jena** [comment]
Thanks for the response again. I finally understand. So basically, if I want the (u,v) coordinates corresponding to "basicmodel_neutral_lbs_10_207_0_v1.0.0.pkl" that conforms to the mapping function used in DecoMR, should I basically do 
uv = 1 - np.array(obj_full['texcoords']) since in your IUV render method, you created an instance of the UVRenderer class as follows : 

renderer = UVRenderer(faces=face, tex=np.zeros([256, 256, 3]), vt=1 - vt, ft=vt_face)  

I am also curious to know why you did vt=1 - vt. I'd be grateful if you could let me know.

**Comment by zengwang430521** [comment]
No, you don not need to do this. 

Actually, we add this line because the property of the render we use. 
I'm sorry  that I did not explain it clearly  in the codes. You can find more detains this [issue](https://github.com/zengwang430521/DecoMR/issues/8).
