### ISSUE TITLE
How to preprocess SURREAL?

### ISSUE THREAD

**Issue by shyanguan** [zengwang430521/DecoMR#2]
Hi @zengwang430521 , nice work! But there is no script that preprocesses SURREAL. Could you share it?

**Comment by zengwang430521** [comment]
OK, I will update soon.

**Comment by shyanguan** [comment]
Thanks!

**Comment by zengwang430521** [comment]
I have update the code about SURREAL dataset, and the pretrained model is also provided here. https://drive.google.com/drive/folders/1xWBVfQa7OZ14VgT9BVO9Lj_kDqRAcQ-e
If there is any problem in the codes, feel free to contact me.

**Comment by shyanguan** [comment]
Copy that! Thanks!
