### ISSUE TITLE
Network initialization

### ISSUE THREAD

**Issue by wangzheallen** [zengwang430521/DecoMR#21]
I search around and only find resnet is initialized, may I ask how is other part  like 'ConvBottleNeck' initialized ?
https://github.com/zengwang430521/DecoMR/blob/69b5986d8545097cf607bd9e6f2f836de7434ce5/models/layers.py#L42

**Comment by zengwang430521** [comment]
Hi, we did not initialize other part with a specific way. These parts are initialized by the default initialization method when creating them.
