### ISSUE TITLE
what is the meaning of tv_loss?

### ISSUE THREAD

**Issue by wangzheallen** [zengwang430521/DecoMR#22]
definition of tv_loss: https://github.com/zengwang430521/DecoMR/blob/69b5986d8545097cf607bd9e6f2f836de7434ce5/train/base_trainer.py#L246
it is with weight 0.0001 when training on up-3d.
I am not sure about the meaning of the loss.

Will this loss only apply only at uv_res 128 or less? If I have a uv_res at 256, does that mean we can get rid of the loss?

**Comment by zengwang430521** [comment]
Hi, tv_loss is only a _total variation regularizer_. This loss item has very little effect to the performance. We add this loss item to make the estimated location map look better in unsupervised area.
