### ISSUE TITLE
Want to get the Human3.6m IUV Map

### ISSUE THREAD

**Issue by Xbbei** [zengwang430521/DecoMR#23]
Hi,
Thanks the great work! You propose the Boundary Free IUV Map to replace the DensePose IUV Map. I agree you said the BF IUV Map is more continuous than the DensePose IUV. So I want to use BF IUV Map. But you only provide the 56x56 pred_IUV Map, It is not accurate for me. I want to tranining the generating BF IUV Map model to satisfy my needed. Could you provide the BF IUV Map Datasets?

Thanks very much!

**Comment by zengwang430521** [comment]
Hi, 
I'm sorry for my late reply.  
The IUV image rendered using GT mesh can be found [here](https://drive.google.com/drive/folders/1HcNU_zethsqZ4MQy_CvL2ozSn_c2vaR5?usp=sharing).

**Comment by Xbbei** [comment]
Thank you your reply. It is very useful for me. I read the Human3.6m paper, and found Human3.6m dataset have the tof depth image, but I download the [https://drive.google.com/drive/folders/1kgVH-GugrLoc9XyvP6nRoaFpw3TmM5xK](url) have not the depth image, So can you provide the Human3.6m depth image? 

Thank you very much

**Comment by zengwang430521** [comment]
I'm sorry that we are not allowed to redistribute the data and we did not download the depth image either. You may need to download the data from the website of Human3.6M.

**Comment by Xbbei** [comment]
> I'm sorry that we are not allowed to redistribute the data and we did not download the depth image either. You may need to download the data from the website of Human3.6M.

Ok, Anyway, Thanks very much!
