### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Saafke** [zengwang430521/DecoMR#30]
Hi Zeng Wang,

Thanks for this great work! What is the license for this repository? If you could add it, that would be greatly appreciated. Thanks in advance. 

FYI - [here's](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository) what happens if a repository has no license:
_"You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work."_

Best,
Saafke

**Comment by zengwang430521** [comment]
Hi, I  have added the Apache License 2.0. Thanks for your kind notice.
