### ISSUE TITLE
A potential problem of warp_feature

### ISSUE THREAD

**Issue by longbowzhang** [zengwang430521/DecoMR#4]
Hi @zengwang430521 ,
I noticed that in your implementation of the warp_feature, a single element in the output transferred F_{uv} could potentially correspond to multiple elements in the local feature F_{im}.
For example, the u,v coordinate of a element in F_{uv} is [16,16]. While in the IUV image, the u,v coordinates are of **float** type. Then, rounding is required  to create the correspondence, and thus multiple locations in the IUV image (e.g., an element with [u,v] = [16.1, 16.6] and another element with [u,v] = [16.4, 16.7]). Then two locations in F_{im} correspond to the single location in the F_{uv}.

Therefore, I am wondering which feature vectors will be transferred?

Best.

**Comment by zengwang430521** [comment]
Hi, @longbowzhang ,
You are right, multiple pixels in local feature map may be warpped to the same location in the UV space. In this case, the transferred feature is the mean of these feature vectors.

**Comment by longbowzhang** [comment]
Hi @zengwang430521,
Thanks a lot for your fast reply.
Then I have a follow-up question after checking the implementation of warp_feature.
https://github.com/zengwang430521/DecoMR/blob/1bcc3bf3b348fe992b720c7fec52e724df7e73a7/models/dense_cnn.py#L19-L66

Maybe I overlook something, but I cannot find the **_mean_** operation as you have mentioned 

> mean of these feature vectors


Therefore, could you elaborate a little bit more on this?

Best.

**Comment by zengwang430521** [comment]
Hi @longbowzhang ,
For a location with multiple transferred feature vectors, with _torch.index_add()_  function, multiple feature vectors will be added to the same location of _warped_feature_. And _warped_w_ is used to count the feature vectors added to every location.
So with _warped_feature = warped_feature / (warped_w + 1e-8)_, we get the mean of multiple feature vectors.

I will add more comments for this function later.
