### ISSUE TITLE
Missing file 'up_3d_trainval.npz'

### ISSUE THREAD

**Issue by wangzheallen** [zengwang430521/DecoMR#7]
Missing file 'up_3d_trainval.npz' when I run 
'python preprocess_datasets.py --gt_iuv'

I do not see the 'Bboxes' in original H36M website, can you also provide the 'Bboxes'

**Comment by zengwang430521** [comment]
You may need to generate 'up_3d_trainval.npz' with the command  `python preprocess_datasets.py --train_files` first.

Or you can download the annotation files from [SPIN](https://github.com/nkolot/SPIN). We use the same codebase with the SPIN, so the annotation files of SPIN are also compatible with our codes.

**Comment by wangzheallen** [comment]
It works! thanks!
