### ISSUE TITLE
Will the code of constructing new UV map / new obj file be released

### ISSUE THREAD

**Issue by wangzheallen** [zengwang430521/DecoMR#9]
Will the code of constructing new UV map / new obj file be released?

**Comment by zengwang430521** [comment]
Our UV map is build with open-source mapping algorithm [Simplicial Complex Augmentation Framework For Bijective Maps](https://libigl.github.io/tutorial/). You can find the tutorial there. 

And the obj file is just the standard obj file. I think it's easy for you to get the code of producing an obj file, both in python and matlab.

Our UV generator can be used for new mesh and new UV map. You only need  to ensure that the UV coordinates is normalized to [0, 1].

**Comment by wangzheallen** [comment]
Thanks for the clarification! :+1:
